# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BDSNhom6' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BDSNhom6

  pod 'SideMenu'
  pod "NohanaImagePicker"
  pod 'SwiftyJSON'
  pod 'ImageSlideshow', '~> 1.4'
  pod 'Alamofire', '~> 4.5'

end
